### ISSUE TITLE
Indent level not preserved after re-enabling postinstall script

### ISSUE THREAD

**Issue by chimericdream** [typicode/pinst#10]
In my projects (both personal and work), I have my indentation level set to 4 spaces. However, it looks like this script is hard-coded to write the `package.json` file out with 2 spaces. It would be nice if it detected the indentation level automatically so I didn't have to add `git reset head --hard` to the `postpublish` script along with `pinst --enable`.

Thanks!

**Comment by typicode** [comment]
Hi @chimericdream,

I've published a new version, should be good.
