### ISSUE TITLE
preinstall

### ISSUE THREAD

**Issue by ozum** [typicode/pinst#13]
Hi,

Is it possible to add `preinstall` script?

(dev only preinstall hooks)

Thanks,

**Comment by typicode** [comment]
Hi,

I think it's going to fail as `pinst` command won't yet be installed. You can add it to a `postinstall` script though.

**Comment by ozum** [comment]
> I think it's going to fail as pinst command won't yet be installed.

@typicode Why?

`pinst` would have been already installed at the time of `prepublishOnly` and `postpublish`. `pinst` will do its job during `prepublishOnly` and `postpublish`.

For example:

```json
// package.json
{
  "scripts": {
    "preinstall": "<some dev only command needed in preinstall step>",
    "postinstall": "<some dev only command>",
    "prepublishOnly": "pinst --disable",
    "postpublish": "pinst --enable"
  }
}
```

**Comment by typicode** [comment]
My bad I misunderstood

**Comment by ozum** [comment]
Added a PR here: https://github.com/typicode/pinst/pull/14

**Comment by typicode** [comment]
Out of curiosity, what would be the use case?

**Comment by ozum** [comment]
Actually, I have a very important use case currently.

I developed a utility called [not-sync](https://www.npmjs.com/package/not-sync) and its CLI [not-sync-cli](https://www.npmjs.com/package/not-sync-cli). This module automatically disables the sync of required paths from the cloud (iCloud, DropBox, or OneDrive). If the target is not in a cloud path, it doesn't change anything.

I'm developing my projects in iCloud Drive and don't want to sync `node_modules`, `dist`, and `coverage`. It takes space, time, and CPU power to sync those unnecessary folders:

(For iCloud) Following command disables sync of `node_modules` by renaming it as `node_modules.nosync` and creating a symbolic link in place of `node_modules`.

```ts
$ not-sync node_modules
```

So I put it in the `preinstall` script with `npx`. I could put it in the "postinstall", but then unnecessary syncing occurs until `not-sync` kicks in. Below is my `package.json`

For example:

```json
{
  "name": "pg-structure",
  "scripts": {
    "preinstall": "npx not-sync node_modules",
    "postinstall": "is-ci || husky install",
    "prepublishOnly": "pinst --disable",
    "postpublish": "pinst --enable"
  }
}
```

As a result, syncing does not start at all.

I want to disable `preinstall` script using `pinst`, because I use `not-sync` only during development and I don't want it to be executed for consumers of `pg-structure`.

**Comment by typicode** [comment]
Thanks for the details. I think I'd rather keep it focused on postinstall. That said, if there's many request for this, it may be revisited.

Feel free to fork as well.

**Comment by cirocfc** [comment]
It would be nice to use npx, yarn dlx, pnpx or else to run this cli on preinstall, to use preinstall only in development and avoid it going to the registry with it...

BTW, someone created a fork and added it to pinst https://github.com/phiberber/pinst
