### ISSUE TITLE
Define dev only command with users only command at the same time.

### ISSUE THREAD

**Issue by vivaxy** [typicode/pinst#15]
Is there some way we can define dev only command with users only command at the same time?

```json
{
  "scripts": {
	"postinstall_for_users": "<some scripts only run on when users install the package>",
	"postinstall_for_dev": "<some dev command>"
  }
}
```

**Comment by typicode** [comment]
Not sure to understand the question. I'd `postinstall`  for users downloading your package from `npm` and `prepare` for the project's devs.
